# Generated by Django 4.1.1 on 2022-10-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='address',
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='mob',
            field=models.BigIntegerField(),
        ),
    ]
